#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
SECRETS_DIR="${SCRIPT_DIR}/secrets"
COMPOSE_FILE="${SCRIPT_DIR}/docker-compose.yml"

print_usage() {
  cat <<'EOF'
Configura los secrets y el archivo .env de MongoDB.

Uso:
  bash setup.sh
  bash setup.sh --help
EOF
}

fail() {
  printf 'Error: %s\n' "$1" >&2
  exit 1
}

prompt_value() {
  local prompt="$1"
  local default_value="$2"
  local value

  read -r -p "${prompt} [${default_value}]: " value
  value="${value:-${default_value}}"
  [[ -n "${value}" ]] || fail "El valor no puede estar vacío."
  [[ "${value}" != *$'\n'* ]] || fail "El valor no puede contener saltos de línea."
  printf '%s' "${value}"
}

prompt_secret() {
  local label="$1"
  local value
  local confirmation

  while true; do
    read -r -s -p "${label}: " value
    printf '\n' >&2
    [[ -n "${value}" ]] || { printf 'El valor no puede estar vacío.\n' >&2; continue; }
    read -r -s -p "Repite ${label}: " confirmation
    printf '\n' >&2
    [[ "${value}" == "${confirmation}" ]] && {
      printf '%s' "${value}"
      return
    }
    printf 'Los valores no coinciden. Inténtalo de nuevo.\n' >&2
  done
}

confirm() {
  local prompt="$1"
  local answer

  read -r -p "${prompt} [s/N]: " answer
  [[ "${answer}" =~ ^[sS]([iI])?$ ]]
}

validate_port() {
  local port="$1"

  [[ "${port}" =~ ^[0-9]+$ ]] || fail "MONGO_HOST_PORT debe ser un número."
  (( port >= 1 && port <= 65535 )) || fail "MONGO_HOST_PORT debe estar entre 1 y 65535."
}

write_secret() {
  local path="$1"
  local value="$2"

  printf '%s\n' "${value}" > "${path}"
  chmod 600 "${path}"
}

[[ "${1:-}" != "--help" ]] || { print_usage; exit 0; }
[[ "${1:-}" == "" ]] || { print_usage >&2; exit 1; }

printf '%s\n' 'Configuración interactiva de MongoDB'
printf '%s\n\n' "Los archivos se crearán en ${SCRIPT_DIR}."

mkdir -p "${SECRETS_DIR}"
chmod 700 "${SECRETS_DIR}"

if [[ -e "${ENV_FILE}" || -e "${SECRETS_DIR}/mongo_root_username" || -e "${SECRETS_DIR}/mongo_root_password" ]]; then
  confirm 'Ya existe una configuración. ¿Deseas sobrescribirla?' || {
    printf '%s\n' 'Operación cancelada.'
    exit 0
  }
fi

printf '%s\n' 'Secrets de MongoDB (la contraseña no se mostrará)'
mongo_root_username="$(prompt_value 'Usuario root' 'admin')"
mongo_root_password="$(prompt_secret 'Contraseña root')"

printf '\n%s\n' 'Configuración de Compose'
compose_project_name="$(prompt_value 'Nombre del proyecto Compose' 'mongodb-dev')"
mongo_container_name="$(prompt_value 'Nombre del contenedor' 'mongodb-dev')"
mongo_image_tag="$(prompt_value 'Versión de MongoDB' '8.0')"
mongo_host_port="$(prompt_value 'Puerto del host' '27017')"
validate_port "${mongo_host_port}"
mongo_volume_name="$(prompt_value 'Nombre del volumen' 'mongodb_data')"
mongo_database="$(prompt_value 'Nombre de la base de datos' 'app')"

printf '\n%s\n' 'Configuración de Mongo Express'
mongo_express_image_tag="$(prompt_value 'Versión de Mongo Express' '1.0.2')"
mongo_express_container_name="$(prompt_value 'Nombre del contenedor web' 'mongo-express-dev')"
mongo_express_host_port="$(prompt_value 'Puerto web del host' '8081')"
validate_port "${mongo_express_host_port}"
mongo_express_cookie_secret="$(prompt_secret 'Secret de cookies web')"
mongo_express_session_secret="$(prompt_secret 'Secret de sesión web')"

write_secret "${SECRETS_DIR}/mongo_root_username" "${mongo_root_username}"
write_secret "${SECRETS_DIR}/mongo_root_password" "${mongo_root_password}"
write_secret "${SECRETS_DIR}/mongo_express_mongodb_url" "mongodb://${mongo_root_username}:${mongo_root_password}@mongodb:27017/?authSource=admin"

cat > "${ENV_FILE}" <<EOF
# Generated by mongodb/setup.sh
COMPOSE_PROJECT_NAME=${compose_project_name}
MONGO_CONTAINER_NAME=${mongo_container_name}
MONGO_IMAGE_TAG=${mongo_image_tag}
MONGO_HOST_PORT=${mongo_host_port}
MONGO_VOLUME_NAME=${mongo_volume_name}
MONGO_DATABASE=${mongo_database}
MONGO_EXPRESS_IMAGE_TAG=${mongo_express_image_tag}
MONGO_EXPRESS_CONTAINER_NAME=${mongo_express_container_name}
MONGO_EXPRESS_HOST_PORT=${mongo_express_host_port}
MONGO_EXPRESS_COOKIE_SECRET=${mongo_express_cookie_secret}
MONGO_EXPRESS_SESSION_SECRET=${mongo_express_session_secret}
EOF
chmod 600 "${ENV_FILE}"

printf '\n%s\n' 'Configuración creada correctamente.'
printf '  .env: %s\n' "${ENV_FILE}"
printf '  secrets: %s\n' "${SECRETS_DIR}"

if confirm '¿Quieres validar la configuración con Docker Compose?'; then
  docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" config --quiet
  printf '%s\n' 'La configuración de Docker Compose es válida.'
fi

if confirm '¿Quieres arrancar MongoDB ahora?'; then
  docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" up -d
  docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" ps
else
  printf '%s\n' "Para arrancar después: docker compose --env-file .env -f docker-compose.yml up -d"
fi